language: objective-c
xcode_workspace: ConnectStats.xcworkspace
xcode_scheme: ConnectStats
osx_image: xcode11
before_install: 
- pod repo update
script:
#- xcodebuild -sdk macosx -workspace ConnectStats.xcworkspace -scheme FitFileExplorer build CODE_SIGNING_REQUIRED=NO
#- Xcodebuild -sdk iphonesimulator -workspace ConnectStats.xcworkspace -scheme HealthStats build CODE_SIGNING_REQUIRED=NO -quiet
- xcodebuild -sdk iphonesimulator -workspace ConnectStats.xcworkspace -scheme ConnectStats -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.2' build CODE_SIGNING_REQUIRED=NO
