language: objective-c
xcode_workspace: ConnectStats.xcworkspace
xcode_scheme: ConnectStats
osx_image: xcode9.3beta
before_install: 
- pod repo update
script:
#- xcodebuild -sdk iphonesimulator -workspace ConnectStats.xcworkspace -scheme ConnectStats build CODE_SIGNING_REQUIRED=NO | grep '^.\[1m'
#- xcodebuild -sdk macosx -workspace ConnectStats.xcworkspace -scheme FitFileExplorer build | grep '.\[1m'
#- xcodebuild -sdk iphonesimulator -workspace ConnectStats.xcworkspace -scheme HealthStats build CODE_SIGNING_REQUIRED=NO | grep '^.\[1m'
- xcodebuild -sdk iphonesimulator -workspace ConnectStats.xcworkspace -scheme ConnectStats -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.2' build test CODE_SIGNING_REQUIRED=NO
