
name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Pre Build
      run: |
        pwd
        ls
        pod install
    - name: Build
      run: xcodebuild -sdk iphonesimulator -workspace ConnectStats.xcworkspace -scheme ConnectStats -destination 'generic/platform=iOS Simulator' build CODE_SIGNING_REQUIRED=NO
